### ISSUE TITLE
"Integrity check" on all files

### ISSUE THREAD

**Issue by szepeviktor** [brefphp/aws-lambda-layers#106]
> This action prevents earthquakes.

Would you merge a workflow that digs down to byte-level and pats every byte's back?

1. File permissions
2. EditorConfig
3. Git conflict markers
4. Move TODO-s into GitHub issues
5. Exported files (GitHub ZIP)
6. And more

https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/reusable-integrity.yml#L39

**Comment by mnapoli** [comment]
I don't understand this issue.

**Comment by szepeviktor** [comment]
I go on and close this one.

**Comment by szepeviktor** [comment]
All right I see :)

I am not your man. I do only long-term stuff usually outside of the bubble of current bugs.
