### ISSUE TITLE
Unable to load APCu extension

### ISSUE THREAD

**Issue by marcguyer** [brefphp/aws-lambda-layers#29]
**Description:**

APCu extension is unavailable in the runtime.

**How to reproduce:**

Following current docs: https://bref.sh/docs/environment/php.html#extensions

* upgrade to v2 plugin 
* (uses layer `arn:aws:lambda:eu-central-1:534081306603:layer:php-81:12`)
* add `extension=apcu` to `./php/conf.d/php.ini`
* deploy a function which uses APCu
* test the function

**Error message:**

```
{
  "errorType": "Error",
  "errorMessage": "Call to undefined function apcu_fetch()",
...
```

```
Warning: PHP Startup: Unable to load dynamic library 'apcu' (tried: /usr/lib64/php/modules/apcu (/usr/lib64/php/modules/apcu: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/apcu.so (/usr/lib64/php/modules/apcu.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by mnapoli** [comment]
From what I tested this should be solved now! I also added tests to ensure this is covered moving forward.

Thanks again for testing!
