### ISSUE TITLE
Can we also install Pcov by default in the fpm-dev image?

### ISSUE THREAD

**Issue by ghost** [brefphp/aws-lambda-layers#92]
Pcov has a considerable performance improvement on generating coverage compared to Xdebug.
So I think it would be great to have this installed by default just like Xdebug so people can choose what to use.

For example also see: https://dyrynda.com.au/blog/using-pcov-instead-of-xdebug-for-coverage

**Comment by mnapoli** [comment]
We could, let's keep this issue open to track interest in such a change.

**Comment by GrahamCampbell** [comment]
Newer versions of xdebug are much faster for code coverage, due to optimizations and the ability to put xdebug in a coverage specific mode, without its other features. The poster of this issue has deleted their account and there is no other interest. I think we can probably close this out.
